---
- name: Install plank
  apt:
    name: plank
    state: present
    update_cache: yes

- name: Install plank themes
  command: cp -R /var/lib/ansible-workstation-assets/plank/themes/ /usr/share/plank/
  changed_when: False

- name: Create /etc/dconf/db/local.d/01-dock1
  template:
    src: 01-dock1.j2
    dest: /etc/dconf/db/local.d/01-dock1

- name: Update dconf
  command: dconf update

- name: Create /etc/xdg/autostart/plank.desktop
  template:
    src: autostart.j2
    dest: /etc/xdg/autostart/plank.desktop
