---
- name: Add flat-remix repository
  apt_repository:
    repo: ppa:daniruiz/flat-remix

- name: Install flat-remix
  package:
    name: flat-remix
    state: present
    update_cache: true

- name: Install flat-remix-gtk
  package:
    name: flat-remix-gtk
    state: present
    update_cache: false

- name: Install flat-remix-gnome
  package:
    name: flat-remix-gnome
    state: present
    update_cache: false

- name: Install libglib2.0-dev-bin
  package:
    name: libglib2.0-dev-bin
    state: present
    update_cache: false

- name: Install imagemagick
  package:
    name: imagemagick
    state: present
    update_cache: false

- name: Clone flat-remix-gnome
  shell: git clone https://github.com/daniruiz/flat-remix-gnome.git /var/lib/flat-remix-gnome || cd /var/lib/flat-remix-gnome && git pull
#  git:
#    repo: 'https://github.com/daniruiz/flat-remix-gnome.git'
#    dest: /tmp/flat-remix-gnome
#    update: yes
#    version: "20191116"
#    accept_hostkey: yes
#    recursive: false
  changed_when: False

- name: Update login-background
  shell: cd /var/lib/flat-remix-gnome/src/assets && find . -type f -name "login-background" -exec cp -T /var/lib/ansible-workstation-assets/wallpapers/{{ wallpaper }}/login-background {} \;
  when: (wallpaper != "")

- name: Install flat-remix-gnome
  shell: cd /var/lib/flat-remix-gnome && make && make install

- name: Copy default wallpaper
  shell: cp /var/lib/ansible-workstation-assets/wallpaper/{{ wallpaper }}/{{ wallpaper }}.jpg /usr/share/backgrounds/{{ wallpaper }}.jpg
  when: (wallpaper != "")

- name: Create /etc/dconf/db/local.d/01-background
  template:
    src: 01-background.j2
    dest: /etc/dconf/db/local.d/01-background
  when: (wallpaper != "")

- name: Create /etc/dconf/db/local.d/01-screensaver
  template:
    src: 01-screensaver.j2
    dest: /etc/dconf/db/local.d/01-screensaver
  when: (wallpaper != "")

- name: Update dconf
  command: dconf update
