---
- name: Check if google-chrome-stable is installed
  command: dpkg-query -W google-chrome-stable
  register: google_chrome_stable
  changed_when: False
  failed_when: False

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: (google_chrome_stable.rc > 0)
