---
- name: Get Ubuntu release number
  command: lsb_release -s -r
  register: lsb_release
  changed_when: False
  failed_when: False

- name: Get Ubuntu release number, LTS
  shell: echo "$(lsb_release -s -r | sed 's/..$//')04"
  register: lsb_release_lts
  changed_when: False
  failed_when: False

- name: Update apt package list
  apt:
    update_cache: yes
  changed_when: False
  failed_when: False

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: no

- name: Install git
  apt:
    name: git
    state: present
    update_cache: no

- name: Clone ansible-workstation-assets
  git:
    repo: 'https://github.com/shawnallen85/ansible-workstation-assets.git'
    dest: /var/lib/ansible-workstation-assets
    update: yes
  changed_when: False

- name: Install gnome-tweak-tool
  apt:
    name: gnome-tweak-tool
    state: present
    update_cache: no

- name: Install gnome-shell-extensions
  apt:
    name: gnome-shell-extensions
    state: present
    update_cache: no

- name: Check if google-chrome-stable is installed
  command: dpkg-query -W google-chrome-stable
  register: google_chrome_stable
  changed_when: False
  failed_when: False

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: (google_chrome_stable.rc > 0)

- name: Check if gitkraken is installed
  command: dpkg-query -W gitkraken
  register: gitkraken
  changed_when: False
  failed_when: False

- name: Install GitKraken
  apt:
    deb: https://release.gitkraken.com/linux/gitkraken-amd64.deb
  when: (gitkraken.rc > 0)

- name: Install nautilus-dropbox
  apt:
    name: nautilus-dropbox
    state: present
    update_cache: no
