---
- name: Get Ubuntu release number
  command: lsb_release -s -r
  register: lsb_release
  changed_when: False
  failed_when: False

- name: Get Ubuntu release number, LTS
  shell: echo "$(lsb_release -s -r | sed 's/..$//')04"
  register: lsb_release_lts
  changed_when: False
  failed_when: False

- name: Update apt package list
  apt:
    update_cache: yes
  changed_when: False
  failed_when: False

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: no

- name: Install git
  apt:
    name: git
    state: present
    update_cache: no

- name: Clone ansible-workstation-assets
  git:
    repo: 'https://github.com/shawnallen85/ansible-workstation-assets.git'
    dest: /var/lib/ansible-workstation-assets
    update: yes
  changed_when: False

- name: Install gnome-tweak-tool
  apt:
    name: gnome-tweak-tool
    state: present
    update_cache: no

- name: Install gnome-shell-extensions
  apt:
    name: gnome-shell-extensions
    state: present
    update_cache: no

- name: Install flatpak
  apt:
    name: flatpak
    state: present
    update_cache: no

- name: Install gnome-software-plugin-flatpak
  apt:
    name: gnome-software-plugin-flatpak
    state: present
    update_cache: no

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install snapd
  apt:
    name: snapd
    state: present
    update_cache: no
