---
- name: Get Ubuntu release number
  command: lsb_release -s -r
  register: lsb_release

- name: Get Ubuntu release number, LTS
  shell: echo "$(lsb_release -s -r | sed 's/..$//')04"
  register: lsb_release_lts

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Check if apt-transport-https is installed
  command: dpkg-query -W apt-transport-https
  register: apt_transport_https
  failed_when: apt_transport_https.rc > 1
  changed_when: apt_transport_https.rc == 1

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
  when: (apt_transport_https.rc > 0)