---
- name: Add manuelschneid3r apt key
  shell: curl -L https://build.opensuse.org/projects/home:manuelschneid3r/public_key | apt-key add -
  changed_when: False
  args:
    warn: no

- name: Add manuelschneid3r repository
  shell: echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_{{ lsb_release.stdout }}/ /' > /etc/apt/sources.list.d/manuelschneid3r.list
  changed_when: False

- name: Install albert
  package:
    name: albert
    state: present
    update_cache: true

- name: Create /etc/xdg/autostart/albert.desktop
  template:
    src: autostart.j2
    dest: /etc/xdg/autostart/albert.desktop
